#' CDBgenerateAcc
#' @title CDBgenerateAcc
#' @param key Character . key generated by CDBgenerateKey()
#' @return Character . A DID repesenting the account
#' @export
#' @examples acc <- CDBgenerateAcc(key)

CDBgenerateAcc <- function(key = NULL){
        if (is.null(key)) stop("key cannot be NULL")
        system(sprintf("composedb did:from-private-key %s", key), intern = TRUE)
}
