

#' start_ceramic
#'
#' @return
#' @export
#'
#' @examples start_ceramic()

start_ceramic <- function(){
        system("npx @ceramicnetwork/cli daemon")
}

#' getCeramicStatus
#'
#' @param key Character.
#' @param url Character.
#'
#' @return
#' @export
#'
#' @examples
#' getCeramicStatus()

getCeramicStatus <- function(key, url = "http://localhost:7007/"){
        system(sprintf("curl -H 'Authorization: Bearer %s' %sapi/v0/admin/status",
                       key, url))
}

# model:content
# http://localhost:7007/api/v0/streams/kjzl6hvfrbw6c8pwn8vkbueq611nkptorifzqhog6e5b4z01fzuynuw00edzx4v?sync=0

#' @title getCeramicProfile
#' @param file Character. Location of daemon.config.json. Default ~/.ceramic/daemon.config.json
#' @return list
#' @export
#' @examples profile <- getCeramicProfile(file = "~/.ceramic/daemon.config.json")

getCeramicProfile <- function(file = "~/.ceramic/daemon.config.json"){
        jsonlite::fromJSON(file)
        }

#' @title CDBgenerateKey
#' @return Character
#' @export
#' @examples key <- CDBgenerateKey()

CDBgenerateKey <- function(){
        system("composedb did:generate-private-key", intern = TRUE)
}

#' @title CDBgenerateAcc
#' @param key Character . key generated by CDBgenerateKey()
#' @return Character . A DID repesenting the account
#' @export
#' @examples acc <- CDBgenerateAcc(key)

CDBgenerateAcc <- function(key = NULL){
        if (is.null(key)) stop("key cannot be NULL")
        system(sprintf("composedb did:from-private-key %s", key), intern = TRUE)
}

#' @title getCeramicAccFromProfile
#' @param file Character. Location of daemon.config.json. Default ~/.ceramic/daemon.config.json
#' @return Character. DID
#' @export
#' @examples acc1 <- getCeramicAccFromProfile()

getCeramicAccFromProfile <- function(file = "~/.ceramic/daemon.config.json"){
        profile <- jsonlite::fromJSON(file)
        profile$`http-api`$`admin-dids`
}

#' @title updateCeramicConfig
#' @param file Character  Path to daemon.config.json file. Default:  "~/.ceramic/daemon.config.json"
#' @param variable Character . One of variable = c("anchor", "http-api", "ipfs", "logger",
#' "metrics", "network", "node", "state-store", "indexing"). Default "http-api"
#' @param subvariable Character. Name of subvariable to change or NULL. One off:
#'  list(anchor = "auth-method",
#'      http-api = c("cors-allowed-origins", "admin-dids"),
#'      ipfs = "mode", logger = c("log-level", "log-to-files"),
#'      metrics = "metrics-exporter-enabled",
#'      network = "name",
#'      node = "privateSeedUrl",
#'      state-store = c("mode", "local-directory"),
#'      indexing = c("db", "allow-queries-before-historical-sync", "disable-composedb", "enable-historical-sync"))
#' @param value. Character. Value to set variable[[subvariable]] to.
#' @param outpath Character. Filepath to write output to. If NULL file is written to original location (file)
#' @return json
#' @export
#' @examples updateCeramicConfig(variable = "http-api", subvariable = "admin-dids", value = acc)

updateCeramicConfig <- function(file = "~/.ceramic/daemon.config.json",
                                variable = c("anchor", "http-api", "ipfs", "logger",
                                             "metrics", "network", "node", "state-store",
                                             "indexing")[2],
                                subvariable = NULL, # `admin-dids`
                                value = NULL,
                                outpath = NULL){
        if (!file.exists(file)) stop("file: ", file, " does not exist")
        if (is.null(value)) stop("Value cannot be NULL")
        profile <- getCeramicProfile(file = file)
        if (!variable %in% names(profile)) stop("No such name as ", variable, " in profile")
        if (!is.null(subvariable)){
                if (!subvariable %in% names(profile[[variable]])) stop("No such name as ", subvariable, " in ",
                                                                       variable, " item of profile")
                profile[[variable]][[subvariable]] <- value
        } else {
                if (length(profile[[variable]]) != 1 ) stop("No subvariable given and ", variable,  " has multiple items, namely:\n ",
                                                             paste(names(profile[[variable]]), " "), "\nChoose one as subvariable")
                profile[[variable]] <- value
        }
        if (is.null(outpath)) outpath = file

        jsonlite::write_json(profile, path = outpath)
        message("file written")
        jsonlite::toJSON(profile)
}

#' @title runCeramic
#' @param network Character. Network name
#' @return Runs Ceramic deamon as side effect
#' @export
#' @examples runCeramic()

runCeramic <- function(network = "testnet-clay"){
        system(sprintf('ceramic daemon --network=%s', network), intern = FALSE, wait = FALSE)
}

createStream <- function(did,
                         baseurl = "http://localhost:7007/",
                         api_version = "v0",
                         type = 0,
                         family = "test2"){

        URL <- glue::glue("{baseurl}api/{api_version}/streams")

        JSON <- jsonlite::toJSON(list(type = type,
                                      genesis = list(
                                              header = list(
                                                      family = family,
                                                      controllers = c(did)
                                              ))), auto_unbox = TRUE)

        system(glue::glue("curl {URL} -X POST -d {JSON} -H Content-Type: application/json"))
}

# curl http://localhost:7007/api/v0/streams -X POST -d {"type":0,"genesis":{"header":{"family":"test2","controllers":["did:key:z6Mktmcyt2kxGuPgDXo6AvSHKyj8uq3MV59ojr225wVaTc19"]}}} -H Content-Type: application/json

# composedb composite:create source-schema.graphql --output=my-composite.json

#' @title CDBModelList
#' @param tab Logical
#' @return Charachter
#' @export
#' @examples CDBModelList()

CDBModelList <- function(tab = TRUE, remoteURL = "http://46.101.111.94:7007/"){
        s <- sprintf("composedb model:list %s", ifelse(tab, "--table", ""))

        if (is.null(remoteURL)) system(s ,intern = TRUE)
        else curl::curl(url = remoteURL)
}

#' @title CDBModelCreate
#' @param content !!!!!!!! Figure uit hoe die model gemaak word - vanuit GraphQL ????
#' @param ceramic_url Character. Ceramic URL
#' @param did_private_key Character. Private key that will control model ??
#' @references  https://composedb.js.org/docs/0.3.x/api/commands/cli.model
#' @description Most of the time you shouldn't be using this command directly.
#' Instead, you should first check if a model you need already exists, using Composites Discovery
#' and only if you can't find a model that you need, you should create one indirectly by
#' creating a Composite from a GraphQL Composite Schema.
#' @return
#' @export
#'
#' @examples

CDBModelCreate <- function(content = NULL,
                           ceramic_url = "http://localhost:7007" ,
                           did_private_key = NULL){
        # composedb model:create CONTENT [-c <value>] [-k <value>]
        if (any(is.null(content), is.null(ceramic_url), is.null(did_private_key))) stop("content, ceramic_url or did_private_key cannot be NULL")
        system( sprintf("composedb model:create %s --ceramic_url=%s --did_private_key=%s",
                       content,
                       ceramic_url,
                       did_private_key),
               intern = TRUE)
}

# modelID <- "kjzl6hvfrbw6c5yi3kx386312dpll69hi87xjlhm2t7m6cn7p1y4ojld1e9srgp"
# composedb composite:from-model kjzl6hvfrbw6c5ajfmes842lu09vjxu5956e3xq0xk12gp2jcf9s90cagt2god9 --ceramic-url=http://localhost:7007 --output= my-first-composite-single.json

#' @title compositeFromModelId
#' @param modelID Character.
#' @param ceramic_url Character. Ceramic URL
#' @param did_private_key Character. Private key that will control composite ??
#' @param output name of output file. Default "composite.json"
#' @return Side effect
#' @export
#' @examples compositeFromModelId(modelID = "kjzl6hvfrbw6c5yi3kx386312dpll69hi87xjlhm2t7m6cn7p1y4ojld1e9srgp", did_private_key= acc)

compositeFromModelId <- function(modelID = NULL,
                                 ceramic_url = "http://localhost:7007",
                                 did_private_key = NULL,
                                 output = "composite.json"){
        if (is.null(modelID)) stop("modelID cannot be NULL")
        string <- sprintf("composedb composite:from-model %s --ceramic-url=%s %s%s, output=%s",
                          modelID,
                          ceramic_url,
                          ifelse(is.null(did_private_key), "", "--did-private-key="),
                          ifelse(is.null(did_private_key), "", did_private_key),
                          output)
        message(string)
        system(string, intern = TRUE)
}

